import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { buildCityTierRadiyoFixturePlan } from './city-tier-radiyo-fixture-plan.mjs';

function track(index, durationSeconds) {
  return {
    fileName: `track-${index}.wav`,
    path: `/fixtures/track-${index}.wav`,
    durationSeconds,
    format: 'wav',
    sha256: `hash-${index}`,
  };
}

test('creates a city-tier, five-source fixture and schedules the fixed ten-day lifecycle without writes', () => {
  const plan = buildCityTierRadiyoFixturePlan({
    city: 'Austin',
    state: 'TX',
    musicCommunity: 'Punk',
    startDate: '2026-08-01',
    tracks: Array.from({ length: 9 }, (_, index) => track(index + 1, 300)),
  });

  assert.equal(plan.readiness.readyForStaging, true);
  assert.equal(plan.readiness.totalPlayableSeconds, 2700);
  assert.equal(plan.readiness.distinctSourceCount, 5);
  assert.equal(plan.sourceMapping.length, 5);
  assert.ok(plan.sourceMapping.every((source) => source.playableSeconds <= 900));
  assert.ok(plan.sourceMapping.every((source) => source.trackCount <= 3));
  assert.equal(plan.lifecycleDryRun.schedules.length, 9);
  assert.ok(plan.lifecycleDryRun.schedules.every((entry) => entry.mainRotationEligibleAt === '2026-08-11' || entry.mainRotationEligibleAt === '2026-08-12' || entry.mainRotationEligibleAt === '2026-08-13'));
  assert.deepEqual(plan.safety, {
    audioCopiedIntoGit: false,
    databaseWrites: false,
    providerUploads: false,
    productionWorkerStarted: false,
    statewideOrNationalAggregation: false,
  });
});

test('rejects tracks over six minutes and reports a city fixture shortfall instead of inventing capacity', () => {
  const plan = buildCityTierRadiyoFixturePlan({
    city: 'Austin',
    state: 'TX',
    musicCommunity: 'Punk',
    startDate: '2026-08-01',
    tracks: [track(1, 361), ...Array.from({ length: 4 }, (_, index) => track(index + 2, 300))],
  });

  assert.equal(plan.readiness.readyForStaging, false);
  assert.equal(plan.readiness.meetsDistinctSourceThreshold, false);
  assert.equal(plan.inventory.excludedTracks[0].reason, 'OVER_MAX_TRACK_SECONDS');
  assert.equal(plan.readiness.remainingPlayableSeconds, 1500);
});

test('excludes byte-identical files so filename variants cannot become extra source capacity', () => {
  const duplicated = track(1, 300);
  const plan = buildCityTierRadiyoFixturePlan({
    city: 'Austin',
    state: 'TX',
    musicCommunity: 'Punk',
    startDate: '2026-08-01',
    tracks: [
      duplicated,
      { ...duplicated, fileName: 'track-1-copy.wav', path: '/fixtures/track-1-copy.wav' },
      ...Array.from({ length: 4 }, (_, index) => track(index + 2, 300)),
    ],
  });

  assert.equal(plan.inventory.audioFileCount, 6);
  assert.equal(plan.inventory.uniqueAudioFileCount, 5);
  assert.equal(plan.inventory.eligibleFileCount, 5);
  assert.equal(plan.inventory.excludedTracks[0].reason, 'DUPLICATE_AUDIO_CONTENT');
  assert.equal(plan.readiness.distinctSourceCount, 5);
  assert.equal(plan.readiness.meetsPlayableThreshold, false);
});

test('preserves supplied source groups instead of splitting one artist across fixture slots', () => {
  const tracks = [
    ...Array.from({ length: 2 }, (_, index) => ({ ...track(index + 1, 300), sourceKey: 'artist-a' })),
    ...Array.from({ length: 2 }, (_, index) => ({ ...track(index + 3, 300), sourceKey: 'artist-b' })),
    ...Array.from({ length: 2 }, (_, index) => ({ ...track(index + 5, 300), sourceKey: 'artist-c' })),
    ...Array.from({ length: 2 }, (_, index) => ({ ...track(index + 7, 300), sourceKey: 'artist-d' })),
    { ...track(9, 300), sourceKey: 'artist-e' },
  ];
  const plan = buildCityTierRadiyoFixturePlan({
    city: 'Austin', state: 'TX', musicCommunity: 'Punk', startDate: '2026-08-01', tracks,
  });

  assert.equal(plan.sourceMappingMode, 'provided-source-groups');
  assert.deepEqual(plan.sourceMapping.map((source) => source.sourceKey).sort(), ['artist-a', 'artist-b', 'artist-c', 'artist-d', 'artist-e']);
  assert.equal(plan.readiness.readyForStaging, true);
});

test('accepts a UTF-8 BOM inventory generated by Windows PowerShell', () => {
  const directory = mkdtempSync(join(tmpdir(), 'uprise-radiyo-inventory-'));
  const inventoryPath = join(directory, 'inventory.json');
  writeFileSync(inventoryPath, `\uFEFF${JSON.stringify({ tracks: [] })}`, 'utf8');

  const execution = spawnSync(process.execPath, [
    'apps/api/scripts/inspect-city-tier-radiyo-fixture.mjs',
    '--inventory', inventoryPath,
    '--city', 'Austin', '--state', 'TX', '--music-community', 'Punk',
  ], { cwd: process.cwd(), encoding: 'utf8' });
  assert.equal(execution.status, 2);
  const result = JSON.parse(execution.stdout);
  assert.equal(result.inventory.audioFileCount, 0);
  assert.equal(result.readiness.readyForStaging, false);
});
